### ISSUE TITLE
ERA SİSTEM HATA KODLARI

### ISSUE THREAD

**Issue by tayyarcenn** [erdemarslan/erahazirsitem#3]
A PHP Error was encountered
Severity: Notice

Message: Undefined index: Browser

Filename: models/system_model.php

Line Number: 33

A PHP Error was encountered
Severity: Notice

Message: Undefined index: Crawler

Filename: models/system_model.php

Line Number: 73

A PHP Error was encountered
Severity: Notice

Message: Undefined index: isSyndicationReader

Filename: models/system_model.php

Line Number: 73

BU HATA KODLARINI ORTADAN KALDIRMAK İÇİN NASIL BİR İŞLEM YAPMALIYIZ

**Comment by erdemarslan** [comment]
index.php içerisinde <?php ifadesinin hemen altına
error_reporting(0);
yazıp kaydediniz ve dosyayı tekrar geri yükleyiniz.
